#include "MC_LogChannels.h"

DEFINE_LOG_CATEGORY(LogResourceNode);
DEFINE_LOG_CATEGORY(LogInventory);
DEFINE_LOG_CATEGORY(LogMiningSystem);
DEFINE_LOG_CATEGORY(LogItem);
DEFINE_LOG_CATEGORY(LogCheatManager)
DEFINE_LOG_CATEGORY(LogWidget);